### ISSUE TITLE
manage.py line 14

### ISSUE THREAD

**Issue by igoramidzic** [pineapplegiant/django-blog#1]
Something is broken here.

**Comment by pineapplegiant** [comment]
Bro u using python 3?

**Comment by igoramidzic** [comment]
That might be it

**Comment by pineapplegiant** [comment]
Yeah man it's just a tutorial blog. I'll update the documentation if you
wanna runserver it up.

**Comment by dennybiasiolli** [comment]
@igoramidzic let's try with the following instructions (from Linux or MacOS):

```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

After this you can launch
```
python manage.py migrate
python manage.py runserver
```

And you should have your working environment.

**Comment by pineapplegiant** [comment]
yup
